# Plugins list
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'vaaleyard/tmux-dotbar'

# Settings
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g base-index 0
set -g status-bg black
set -g status-fg white
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
setw -g mode-keys vi
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -sg escape-time 0
set-option -g history-limit 10000

# tmux-dotbar Settings
set -g @tmux-dotbar-bg '#000000'
set -g @tmux-dotbar-fg '#818581'
set -g @tmux-dotbar-fg-current '#ffffff'

set -g @tmux-dotbar-ssh-icon '󰌘'
set -g @tmux-dotbar-ssh-icon-only false
set -g @tmux-dotbar-ssh-enabled true


# Key bindings
set-option -g prefix C-n
bind-key C-n send-prefix
setw -g mode-style 'fg=colour1 bg=colour18 bold' # copy mode
unbind '"'
unbind %
bind '"' split-window -h -c "#{pane_current_path}"
bind '_' split-window -v -c "#{pane_current_path}"

bind-key ] split-window -h -p 30 -c "#{pane_current_path}" \; select-pane -t 2 \; split-window -v -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottem)
run '~/.tmux/plugins/tpm/tpm'
